<?php

namespace Tests\Unit;

use PHPUnit\Framework\TestCase;

/**
 * Verify that composer.json and composer.lock describe the Laravel 13
 * dependency upgrade and the Spatie Query Builder 6 upgrade.
 */
class ComposerDependenciesTest extends TestCase
{
    private array $composerJson;

    private array $composerLock;

    protected function setUp(): void
    {
        parent::setUp();

        $this->composerJson = json_decode(
            file_get_contents(__DIR__.'/../../composer.json'),
            true,
            512,
            JSON_THROW_ON_ERROR
        );

        $this->composerLock = json_decode(
            file_get_contents(__DIR__.'/../../composer.lock'),
            true,
            512,
            JSON_THROW_ON_ERROR
        );
    }

    private function findLockedPackage(string $name): ?array
    {
        foreach ([
            ...($this->composerLock['packages'] ?? []),
            ...($this->composerLock['packages-dev'] ?? []),
        ] as $package) {
            if (($package['name'] ?? null) === $name) {
                return $package;
            }
        }

        return null;
    }

    private function packageVersion(string $name): string
    {
        $package = $this->findLockedPackage($name);

        $this->assertNotNull($package, "{$name} package not found in composer.lock");

        return ltrim($package['version'], 'v');
    }

    // composer.json: declared constraints

    public function test_composer_json_requires_laravel_framework_version_13(): void
    {
        $this->assertSame('^13.0', $this->composerJson['require']['laravel/framework']);
    }

    public function test_composer_json_no_longer_requires_laravel_framework_version_12(): void
    {
        $this->assertNotSame('^12.0', $this->composerJson['require']['laravel/framework']);
    }

    public function test_composer_json_requires_spatie_query_builder_version_6(): void
    {
        $this->assertSame('^6.0', $this->composerJson['require']['spatie/laravel-query-builder']);
    }

    public function test_composer_json_no_longer_requires_spatie_query_builder_version_5(): void
    {
        $this->assertNotSame('^5.7', $this->composerJson['require']['spatie/laravel-query-builder']);
    }

    public function test_composer_json_php_constraint_is_unchanged_by_the_upgrade(): void
    {
        $this->assertSame('^8.3', $this->composerJson['require']['php']);
    }

    public function test_composer_json_unrelated_direct_dependencies_are_untouched(): void
    {
        $this->assertSame('^4.0', $this->composerJson['require']['laravel/sanctum']);
        $this->assertSame('^3.0', $this->composerJson['require']['laravel/tinker']);
        $this->assertSame('^4.23', $this->composerJson['require']['spatie/laravel-data']);
    }

    // composer.lock: content-hash bookkeeping

    public function test_composer_lock_content_hash_matches_the_current_composer_json(): void
    {
        // This is the hash generated by Composer for the committed composer.json.
        $this->assertSame('b1d961e4b790d813ec7b74dac9d8aecd', $this->composerLock['content-hash']);
    }

    public function test_composer_lock_content_hash_is_a_valid_md5_hash(): void
    {
        $this->assertMatchesRegularExpression('/^[a-f0-9]{32}$/', $this->composerLock['content-hash']);
    }

    public function test_composer_lock_platform_php_constraint_matches_composer_json(): void
    {
        $this->assertSame($this->composerJson['require']['php'], $this->composerLock['platform']['php']);
    }

    // composer.lock: Laravel 13

    public function test_laravel_framework_is_locked_to_a_v13_release(): void
    {
        $version = $this->packageVersion('laravel/framework');

        $this->assertStringStartsWith('13.', $version);
        $this->assertFalse(str_starts_with($version, '12.'));
    }

    public function test_laravel_framework_requires_updated_symfony_components(): void
    {
        $require = $this->findLockedPackage('laravel/framework')['require'];

        foreach ([
            'symfony/console',
            'symfony/error-handler',
            'symfony/finder',
            'symfony/http-foundation',
            'symfony/http-kernel',
            'symfony/mailer',
            'symfony/mime',
            'symfony/process',
            'symfony/routing',
            'symfony/uid',
            'symfony/var-dumper',
        ] as $component) {
            $this->assertArrayHasKey($component, $require);
            $this->assertStringContainsString('^7', $require[$component], "Expected {$component} to support Symfony 7");
        }
    }

    public function test_laravel_framework_requires_php84_and_php85_polyfills(): void
    {
        $require = $this->findLockedPackage('laravel/framework')['require'];

        foreach (['symfony/polyfill-php84', 'symfony/polyfill-php85'] as $polyfill) {
            $this->assertArrayHasKey($polyfill, $require);
            $this->assertStringStartsWith('^1.', $require[$polyfill]);
        }
    }

    public function test_laravel_framework_supports_current_brick_math_versions(): void
    {
        $require = $this->findLockedPackage('laravel/framework')['require'];

        $this->assertStringContainsString('^0.14.2', $require['brick/math']);
        $this->assertStringNotContainsString('0.9.3', $require['brick/math']);
        $this->assertStringNotContainsString('0.10.2', $require['brick/math']);
    }

    public function test_laravel_framework_requires_laravel_prompts_three(): void
    {
        $require = $this->findLockedPackage('laravel/framework')['require'];

        $this->assertStringStartsWith('^0.3', $require['laravel/prompts']);
    }

    public function test_laravel_framework_replace_section_includes_new_illuminate_packages(): void
    {
        $replace = $this->findLockedPackage('laravel/framework')['replace'];

        $this->assertSame('self.version', $replace['illuminate/json-schema']);
        $this->assertSame('self.version', $replace['illuminate/reflection']);
    }

    public function test_laravel_framework_autoload_includes_the_new_reflection_component(): void
    {
        $autoload = $this->findLockedPackage('laravel/framework')['autoload'];

        $this->assertContains('src/Illuminate/Reflection/helpers.php', $autoload['files']);
        $this->assertContains('src/Illuminate/Reflection/', $autoload['psr-4']['Illuminate\\Support\\']);
    }

    public function test_laravel_framework_dev_tooling_versions_were_bumped(): void
    {
        $requireDev = $this->findLockedPackage('laravel/framework')['require-dev'];

        $this->assertSame('^11.0.0', $requireDev['orchestra/testbench-core']);
        $this->assertArrayHasKey('phpstan/phpstan', $requireDev);
        $this->assertArrayHasKey('symfony/cache', $requireDev);
    }

    // composer.lock: Spatie Query Builder 6

    public function test_spatie_query_builder_is_locked_to_a_major_version_6_release(): void
    {
        $version = $this->packageVersion('spatie/laravel-query-builder');

        $this->assertStringStartsWith('6.', $version);
        $this->assertFalse(str_starts_with($version, '5.'));
    }

    public function test_spatie_query_builder_supports_laravel_12_and_13(): void
    {
        $require = $this->findLockedPackage('spatie/laravel-query-builder')['require'];

        $this->assertStringContainsString('^12.0', $require['illuminate/database']);
        $this->assertStringContainsString('^13.0', $require['illuminate/database']);
        $this->assertStringContainsString('^12.0', $require['illuminate/http']);
        $this->assertStringContainsString('^12.0', $require['illuminate/support']);
    }

    public function test_spatie_query_builder_still_registers_its_service_provider(): void
    {
        $package = $this->findLockedPackage('spatie/laravel-query-builder');

        $this->assertSame(
            ['Spatie\\QueryBuilder\\QueryBuilderServiceProvider'],
            $package['extra']['laravel']['providers']
        );
    }

    public function test_symfony_polyfill_php84_was_added_as_a_locked_package(): void
    {
        $package = $this->findLockedPackage('symfony/polyfill-php84');

        $this->assertNotNull($package);
        $this->assertContains('bootstrap.php', $package['autoload']['files']);
        $this->assertArrayHasKey('Symfony\\Polyfill\\Php84\\', $package['autoload']['psr-4']);
    }
}
